const enum ACTIONS {
  TURN_LEFT = "TURN_LEFT",
  TURN_RIGHT = "TURN_RIGHT",
  ACCELERATE = "ACCELERATE",
  SHOOT = "SHOOT",
  NOTHING = "NOTHING",
  SHOOT_N_TURN_LEFT = "SHOOT_N_TURN_LEFT",
  SHOOT_N_TURN_RIGHT = "SHOOT_N_TURN_RIGHT",
  ACCELERATE_N_TURN_LEFT = "ACCELERATE_N_TURN_LEFT",
  ACCELERATE_N_TURN_RIGHT = "ACCELERATE_N_TURN_RIGHT",
  ACCELERATE_N_SHOOT = "ACCELERATE_N_SHOOT",
  ACCELERATE_N_SHOOT_N_TURN_LEFT = "ACCELERATE_N_SHOOT_N_TURN_LEFT",
  ACCELERATE_N_SHOOT_N_TURN_RIGHT = "ACCELERATE_N_SHOOT_N_TURN_RIGHT"
} // 12 actions
